### PR TITLE
Problem solved

### PR DESCRIPTION
**Pull request by rsthangavel**
**Technology** : Nodejs

**Problem 1** : Solution available in problem1.js
**Problem 2** : Solution available in problem2.js

**Package used** : fast-csv to read csv data
**Run Command** :

node problem1.js
node problem2.js

**Note**: Please run npm install before executing node command

### CODE REVIEW

**Comment by maknahar** [comment]
Hi Thangavel, Thanks for submitting the solution.

**Comment by maknahar** [comment]
Solution for the first problem works fine. However, the solution for second problem does not match the expected result. Could you check?

**Comment by maknahar** [comment]
Screenshot 2019-09-23 at 6 55 39 PM

**Comment by rsthangavel** [comment]
Hi @maknahar,

I know my second problem is not meet the expected result. But In my point of understanding, if capacity slab exceeds the limit then we need to reassign to a different partner. In my solution, the capacity is still available even after assigning all delivery partner to the capacity.

And also, I'm choosing P1 to D1 and its cost is 2000. Your result choose P2 and its cost is 3000. For cost perspective, my solution looks good.

Available capacity :
[ { 'Partner ID': 'P1          ', 'Capacity (in GB)': 200 },
  { 'Partner ID': 'P2          ', 'Capacity (in GB)': 175 },
  { 'Partner ID': 'P3          ', 'Capacity (in GB)': 990 } ]


Please clarify, if my understanding is wrong.

**Pull request closed without merging**
