### PR TITLE
challange 2019

### PR DESCRIPTION
**Pull request by ravikantpal1408**

### CODE REVIEW

**Comment by maknahar** [comment]
Hi @ravikantpal1408, Thanks for submitting the solution.

**Comment by maknahar** [comment]
Would it be possible to output the result in a CSV file output1.csv and output2.csv as specified in the README file?

**Comment by ravikantpal1408** [comment]
Greetings,
Yes, I can do that.

I'll push my changes as I get home back. I'm currently in my office.
Is that OK?

Thanks

**Comment by maknahar** [comment]
> I'll push my changes as I get home back. I'm currently in my office.

Hi @ravikantpal1408, Please re-request the review when you want me to have a look.

**Comment by ravikantpal1408** [comment]
Greetings,
OK, should I request for review?
Thanks & Regards

**Comment by ravikantpal1408** [comment]
Please review my work,  Thank you.

**Pull request closed without merging**
